function x=plot_rc_obj_dummy( rc_obj, ...
    remove_ends,...
    minlength,...
    Quantity1,...
    Quantity2,...
    figdetails,...
    xlims,...
    ylims,...
    sorting,...
    colors,...
    query,...
    newfig)

x=1

end